spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mulantest
    username: root
    password: mulansql
  session:
    #session存储方式
    store-type: redis
  redis:
    host: 192.168.8.100
    port: 6379
    database: 0
    #redis的超时时间
    timeout: 5000
    password: mulan7146
  # 支持 swagger3
  mvc:
    path match:
      matching-strategy: ant_path_matcher
server:
  port: 8080
  servlet:
    session:
      cookie:
        domain: #cookie跨域设置

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
#    开启sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

page helper:
  # 数据库方言 mysql
  helper-dialect: mysql
  # 分页参数合理化，pageNum<=0 会查询第一页，pageNum>总页数 会查询最后一页
  # reasonable: true
  # 某个地方使用分页后仍然想通过控制参数查询全部的结果，当pageSize=0就会查询出全部的结果
  page-size-zero: true
  #默认count查询在传入参数是0时会让上面想实现的逻辑实效，这项也可以单独查询配置
  default-count: false




## springdoc-openapi项目配置
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    tags-sorter: alpha
#    operations-sorter: alpha
#  api-docs:
#    path: /v3/api-docs
#  group-configs:
#    - group: 'default'
#      paths-to-match: '/**'
#      packages-to-scan: com.mulan.fengwo_backend.controller
## knife4j的增强配置，不需要增强可以不配
#knife4j:
#  enable: true
#  setting:
#    language: zh_cn
